#! /bin/python3.12
import subprocess
import datetime
import re

project_name = input('Имя проекта: ')

while True:
    interval = input('Интервал(1, 2, 3 ...)(d, w, m): ')

    if not interval[0].isdigit() \
            or interval[1] not in ['w', 'd', 'm']:
                continue

    if interval[1] == 'w':
        interval = datetime.timedelta(weeks=int(interval[0]))
    elif interval[1] == 'd':
        interval = datetime.timedelta(days=int(interval[0]))
    else:
        interval = datetime.timedelta(weeks=4 * int(interval[0]))

    break

dat = datetime.datetime.now() + interval

while True:
    task_num = input('Номер этапа("end" что бы закончить, num-num что бы добавить интервал): ')

    if task_num == 'end':
        break
    elif re.fullmatch(r'\d+-\d+', task_num):
        f_num, s_num = int(task_num.split('-')[0]), int(task_num.split('-')[1])
        for i in range(f_num, s_num + 1):
            dat += interval
            subprocess.run(['task', 'add', 'Complete', str(i), f'project:{project_name}', f'due:{dat}'])
    else:
        subprocess.run(['task', 'add', 'Complete', task_num, f'project:{project_name}', f'due:{str(dat).split()[0]}'])
        dat += interval
